import React,{useMemo,useState} from 'react';
import {Activity,BarChart3,ChevronRight,Clock3,BrainCircuit,RefreshCw,ShieldCheck,SlidersHorizontal,Trash2,X,Zap} from 'lucide-react';
import {events} from './domain'; import type {Selection} from './domain'; import {evaluate,potentialReturn,analyzeCore} from './engine'; import './styles.css';

export default function App(){
 const [eventId,setEventId]=useState('e1'); const [sport,setSport]=useState<'All'|'Football'|'Tennis'>('All'); const [picked,setPicked]=useState<Selection[]>([]); const [stake,setStake]=useState(20); const [slip,setSlip]=useState(false); const [aiOpen,setAiOpen]=useState(true);
 const visible=events.filter(e=>sport==='All'||e.sport===sport); const event=events.find(e=>e.id===eventId)??visible[0]; const check=useMemo(()=>evaluate(picked),[picked]); const core=useMemo(()=>analyzeCore(picked,event),[picked,event]);
 function toggle(s:Selection){setPicked(p=>p.some(x=>x.id===s.id)?p.filter(x=>x.id!==s.id):[...p.filter(x=>x.marketId!==s.marketId),s])}
 return <div className="app"><header><div className="brand"><span className="mark">B</span><div><strong>BAD<span>BUILDER</span></strong><small>sports intelligence engine</small></div></div><nav><button className="active">Builder</button><button>Live Data</button><button>Intelligence</button><button>History</button></nav><div className="status"><i/> Core Engine online</div></header>
 <main><section className="hero"><div><p className="eyebrow">BET BUILDER / AI CONTROL ROOM</p><h1>Build smarter.<br/><em>Let the Core Engine audit it.</em></h1><p className="sub">Every selected leg flows through validation, probability, value, volatility and correlation checks before the build reaches review.</p></div><div className="heroCards"><div><span>EVENTS</span><b>03</b><small>tracked now</small></div><div><span>MARKETS</span><b>08</b><small>normalized</small></div><div><span>CORE</span><b>{picked.length?core.confidence+'%':'—'}</b><small>build confidence</small></div></div></section>
 <div className="toolbar"><div className="tabs">{(['All','Football','Tennis'] as const).map(x=><button className={sport===x?'sel':''} onClick={()=>setSport(x)} key={x}>{x}</button>)}</div><button className="ghost"><SlidersHorizontal size={16}/> Filters</button><button className="ghost"><RefreshCw size={15}/> Refresh odds</button></div>
 <div className="workspace"><aside className="events"><div className="sectionHead"><span>UPCOMING EVENTS</span><small>{visible.length} events</small></div>{visible.map(e=><button className={'event '+(event.id===e.id?'chosen':'')} onClick={()=>setEventId(e.id)} key={e.id}><div className="eventTop"><span>{e.sport}</span><time><Clock3 size={12}/>{e.start}</time></div><strong>{e.home}</strong><b>vs</b><strong>{e.away}</strong><div className="league">{e.league}<ChevronRight size={14}/></div></button>)}</aside>
 <section className="markets"><div className="marketTitle"><div><span className="liveDot"/> {event.league}</div><div className="eventName"><strong>{event.home}</strong><span>vs</span><strong>{event.away}</strong></div><small>Start {event.start}</small></div>{event.markets.map(m=><div className="market" key={m.id}><div className="marketHead"><strong>{m.name}</strong><span>2-way / normalized</span></div><div className="selections">{m.selections.map(s=><button key={s.id} disabled={s.status!=='open'} className={'selection '+(picked.some(x=>x.id===s.id)?'selected':'')} onClick={()=>toggle(s)}><span>{s.label}</span><b>{s.odds.toFixed(2)}</b>{picked.some(x=>x.id===s.id)&&<i>✓</i>}</button>)}</div></div>)}
 <div className="intel"><div className="intelIcon"><BrainCircuit/></div><div><strong>Core Engine pipeline</strong><p>Validation → probability → value → volatility → correlation → confidence. The panel below exposes every intermediate signal.</p></div><button className="badgeButton" onClick={()=>setAiOpen(v=>!v)}>{aiOpen?'HIDE':'OPEN'} CORE</button></div>
 {aiOpen&&<section className="corePanel"><div className="coreHeader"><div><span className="eyebrow">CORE ENGINE / BUILD ANALYSIS</span><h3>{picked.length?`Analysis of ${picked.length} selected leg${picked.length===1?'':'s'}`:'Awaiting selections'}</h3></div>{picked.length>0&&<div className={'risk '+core.risk.toLowerCase()}>{core.risk} RISK</div>}</div>{picked.length>0?<><div className="coreMetrics"><div><span>CONFIDENCE</span><strong>{core.confidence}%</strong></div><div><span>MODEL</span><strong>{(core.modelProbability*100).toFixed(1)}%</strong></div><div><span>EDGE</span><strong className={core.edge>0?'good':''}>{(core.edge*100).toFixed(1)}%</strong></div><div><span>VOLATILITY</span><strong>{(core.volatility*100).toFixed(1)}%</strong></div></div><div className="signalGrid">{core.signals.map(s=><div className="signal" key={s.label}><div><span>{s.label}</span><b>{s.value}</b></div><div className="bar"><i style={{width:`${s.score}%`}}/></div><small>{s.detail}</small></div>)}</div><div className="reasoning"><div className="reasonTitle"><Zap size={14}/> DECISION TRACE</div>{core.reasoning.map((r,i)=><div key={i}><b>{String(i+1).padStart(2,'0')}</b><span>{r}</span></div>)}</div></>:<div className="coreEmpty"><BrainCircuit size={20}/><span>Select legs to activate the full analysis pipeline.</span></div>}<div className="coreFooter">LOCAL MODEL · DETERMINISTIC SNAPSHOT · PROVIDER ADAPTER READY</div></section>}
 </section>
 <aside className={'slip '+(slip?'mobileOpen':'')}><div className="slipHead"><div><span>BET BUILDER</span><h2>Your build <sup>{picked.length}</sup></h2></div><button onClick={()=>setSlip(false)} className="close"><X/></button></div>{picked.length===0?<div className="empty"><div><BrainCircuit/></div><strong>Select market legs</strong><p>The Core Engine will validate and analyze the build in real time.</p></div>:<><div className="legs">{picked.map(s=><div className="leg" key={s.id}><div><span>{s.label}</span><small>Open · snapshot locked</small></div><b>{s.odds.toFixed(2)}</b><button onClick={()=>toggle(s)}><Trash2 size={14}/></button></div>)}</div><div className="analysis"><div><span>Combined odds</span><b>{check.combinedOdds.toFixed(2)}</b></div><div><span>Model probability</span><b>{(check.probability*100).toFixed(1)}%</b></div><div><span>Core confidence</span><b>{core.confidence}%</b></div><div><span>Model edge</span><b className={core.edge>0?'positive':''}>{(core.edge*100).toFixed(1)}%</b></div><p className={check.ok&&core.edge>0?'positiveText':''}><ShieldCheck size={14}/>{core.edge>0?`Core Engine detected ${(core.edge*100).toFixed(1)}% adjusted edge.`:check.message}</p></div><label className="stake">Stake<input type="number" min="1" value={stake} onChange={e=>setStake(Number(e.target.value)||1)}/><span>PLN</span></label><div className="return"><span>Potential return</span><strong>{potentialReturn(stake,check.combinedOdds).toFixed(2)} PLN</strong></div><button className="primary" disabled={!check.ok}><Activity size={17}/> {check.ok?'Lock build for review':'Fix validation issues'}</button><small className="disclaimer">Simulation only. Current odds and model probabilities are mock snapshots until live provider and production model adapters connect.</small></>}</aside></div></main><button className="mobileSlip" onClick={()=>setSlip(true)}>Build <b>{picked.length}</b><strong>{check.combinedOdds?check.combinedOdds.toFixed(2):'—'}</strong></button></div>
}
