import React,{useMemo,useState} from 'react';
import {Activity,BarChart3,ChevronRight,Clock3,Minus,Plus,RefreshCw,ShieldCheck,SlidersHorizontal,Trash2,TrendingUp,X} from 'lucide-react';
import {events} from './domain'; import type {Event,Selection} from './domain'; import {evaluate,potentialReturn} from './engine'; import './styles.css';

export default function App(){
 const [eventId,setEventId]=useState('e1'); const [sport,setSport]=useState<'All'|'Football'|'Tennis'>('All'); const [picked,setPicked]=useState<Selection[]>([]); const [stake,setStake]=useState(20); const [slip,setSlip]=useState(false);
 const visible=events.filter(e=>sport==='All'||e.sport===sport); const event=events.find(e=>e.id===eventId)??visible[0]; const check=useMemo(()=>evaluate(picked),[picked]);
 function toggle(s:Selection){setPicked(p=>p.some(x=>x.id===s.id)?p.filter(x=>x.id!==s.id):[...p.filter(x=>x.marketId!==s.marketId),s])}
 return <div className="app"><header><div className="brand"><span className="mark">B</span><div><strong>BAD<span>BUILDER</span></strong><small>sports intelligence engine</small></div></div><nav><button className="active">Builder</button><button>Live Data</button><button>Intelligence</button><button>History</button></nav><div className="status"><i/> Data stream online</div></header>
 <main><section className="hero"><div><p className="eyebrow">BET BUILDER / CONTROL ROOM</p><h1>Build smarter.<br/><em>Validate every leg.</em></h1><p className="sub">Canonical odds, deterministic validation and transparent model signals. No black-box math.</p></div><div className="heroCards"><div><span>EVENTS</span><b>03</b><small>tracked now</small></div><div><span>MARKETS</span><b>08</b><small>normalized</small></div><div><span>DATA QUALITY</span><b>99.2%</b><small>provider health</small></div></div></section>
 <div className="toolbar"><div className="tabs">{(['All','Football','Tennis'] as const).map(x=><button className={sport===x?'sel':''} onClick={()=>setSport(x)} key={x}>{x}</button>)}</div><button className="ghost"><SlidersHorizontal size={16}/> Filters</button><button className="ghost"><RefreshCw size={15}/> Refresh odds</button></div>
 <div className="workspace"><aside className="events"><div className="sectionHead"><span>UPCOMING EVENTS</span><small>{visible.length} events</small></div>{visible.map(e=><button className={'event '+(event.id===e.id?'chosen':'')} onClick={()=>setEventId(e.id)} key={e.id}><div className="eventTop"><span>{e.sport}</span><time><Clock3 size={12}/>{e.start}</time></div><strong>{e.home}</strong><b>vs</b><strong>{e.away}</strong><div className="league">{e.league}<ChevronRight size={14}/></div></button>)}</aside>
 <section className="markets"><div className="marketTitle"><div><span className="liveDot"/> {event.league}</div><div className="eventName"><strong>{event.home}</strong><span>vs</span><strong>{event.away}</strong></div><small>Start {event.start}</small></div>{event.markets.map(m=><div className="market" key={m.id}><div className="marketHead"><strong>{m.name}</strong><span>2-way / normalized</span></div><div className="selections">{m.selections.map(s=><button key={s.id} disabled={s.status!=='open'} className={'selection '+(picked.some(x=>x.id===s.id)?'selected':'')} onClick={()=>toggle(s)}><span>{s.label}</span><b>{s.odds.toFixed(2)}</b>{picked.some(x=>x.id===s.id)&&<i>✓</i>}</button>)}</div></div>)}<div className="intel"><div className="intelIcon"><BarChart3/></div><div><strong>Model context</strong><p>Probability and edge are computed from the canonical selection snapshot. Correlation-aware portfolio logic is next in the pipeline.</p></div><span className="badge">LIVE</span></div></section>
 <aside className={'slip '+(slip?'mobileOpen':'')}><div className="slipHead"><div><span>BET BUILDER</span><h2>Your build <sup>{picked.length}</sup></h2></div><button onClick={()=>setSlip(false)} className="close"><X/></button></div>{picked.length===0?<div className="empty"><div><Plus/></div><strong>Select market legs</strong><p>Pick selections from the market board. The engine validates conflicts automatically.</p></div>:<><div className="legs">{picked.map(s=><div className="leg" key={s.id}><div><span>{s.label}</span><small>Open · snapshot locked</small></div><b>{s.odds.toFixed(2)}</b><button onClick={()=>toggle(s)}><Trash2 size={14}/></button></div>)}</div><div className="analysis"><div><span>Combined odds</span><b>{check.combinedOdds.toFixed(2)}</b></div><div><span>Model probability</span><b>{(check.probability*100).toFixed(1)}%</b></div><div><span>Model edge</span><b className={check.edge>0?'positive':''}>{(check.edge*100).toFixed(1)}%</b></div><p className={check.edge>0?'positiveText':''}><ShieldCheck size={14}/>{check.message}</p></div><label className="stake">Stake<input type="number" min="1" value={stake} onChange={e=>setStake(Number(e.target.value)||1)}/><span>PLN</span></label><div className="return"><span>Potential return</span><strong>{potentialReturn(stake,check.combinedOdds).toFixed(2)} PLN</strong></div><button className="primary" disabled={!check.ok}><Activity size={17}/> {check.ok?'Lock build for review':'Fix validation issues'}</button><small className="disclaimer">Simulation only. Odds are mock snapshots until a live provider adapter is connected.</small></>}</aside></div></main><button className="mobileSlip" onClick={()=>setSlip(true)}>Build <b>{picked.length}</b><strong>{check.combinedOdds?check.combinedOdds.toFixed(2):'—'}</strong></button></div>
}
